services:
  app-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - content-cache:/app/cache/content
      - app-model-cache:/app/cache/models
      - model-cache:/cache/torch
      - huggingface-cache:/cache/huggingface
    environment:
      - PYTHONPATH=/app
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - HF_HOME=/cache/huggingface
      - TRANSFORMERS_CACHE=/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/cache/huggingface
      - TORCH_HOME=/cache/torch
      - CACHE_DIR=/app/cache
    ports:
      - "8501:8501"
    restart: unless-stopped
    command: streamlit run /app/src/book_to_essay/streamlit_app.py
    labels:
      - "org.label-schema.description=CPU version of BusyStudentCompanion"

  app-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    runtime: nvidia
    volumes:
      - content-cache:/app/cache/content
      - app-model-cache:/app/cache/models
      - model-cache:/cache/torch
      - huggingface-cache:/cache/huggingface
    environment:
      - PYTHONPATH=/app
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - HF_HOME=/cache/huggingface
      - TRANSFORMERS_CACHE=/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/cache/huggingface
      - TORCH_HOME=/cache/torch
      - CACHE_DIR=/app/cache
    ports:
      - "8502:8501"
    restart: unless-stopped
    command: /app/start.sh
    labels:
      - "org.label-schema.description=GPU-accelerated BusyStudentCompanion (beta)"

  app-gpu-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - content-cache:/app/cache/content
      - app-model-cache:/app/cache/models
      - model-cache:/cache/torch
      - huggingface-cache:/cache/huggingface
    environment:
      - PYTHONPATH=/app
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - HF_HOME=/cache/huggingface
      - TRANSFORMERS_CACHE=/cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/cache/huggingface
      - TORCH_HOME=/cache/torch
      - CACHE_DIR=/app/cache
    ports:
      - "8503:8501"
    restart: unless-stopped
    command: streamlit run /app/src/book_to_essay/streamlit_app.py
    labels:
      - "org.label-schema.description=Test version simulating GPU code on CPU"

volumes:
  model-cache:
  huggingface-cache:
  content-cache:
  app-model-cache:
